// Generated by CoffeeScript 1.10.0
(function() {
  var postPlanner;

  postPlanner = chrome.contextMenus.create({
    contexts: ['image'],
    title: 'Send to PostPlanner',
    onclick: function(info) {
      return console.log(info.srcUrl);
    }
  });

}).call(this);
